### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by ujeongoh** [FlaschenbookProject/Flaschenbook#16]
### Issue 타입 ('x' 로 표기)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert (Rollback)

### 상세 내용
- Data Warehouse, Production DB의 스키마를 설정합니다.
- 각각 ERD를 작성합니다.

### 예상 소요 시간
- [ ] `0.5h`
- [x] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by ssongjj** [comment]
## 2023-08-11 
### 1 차 
![Image](https://github.com/FlaschenbookProject/Flashenbook/assets/39427152/6735c6de-371d-493e-b53c-0ec134dd1eb4)
### 추가되어야 할 사항
**SparkML로 개인화 추천 서비스를 만들기 위해 유저별로 데이터 정보를 저장할 때 어떤 형식으로 저장하는 것이 효율적일지 추가 학습 후 테이블 설계**
1) 설계 시 생각해야 할 데이터는 처음 회원 가입을 할 때 받는 취향 선택 내용 
2) 생각한 내용은 다양한 책의 정보 (장르, 책 내용, 줄거리, 저자) 등을 선택해 이를 문자열로 저장하는 방법과 책의 구절을 보여 주어 선택한 책의 ISBN을 취향으로 저장하는 방법 두 가지를 생각 중

**로그 데이터 저장하는 테이블 설계**

**Comment by ujeongoh** [comment]
<img width="1262" alt="image" src="https://github.com/FlaschenbookProject/Flaschenbook/assets/103317018/153c119b-4fb7-4b9a-bb19-c8160545cef2">
