### ISSUE TITLE
AWS S3 (Data lake) 환경 구축

### ISSUE THREAD

**Issue by ujeongoh** [FlaschenbookProject/Flaschenbook#22]
### Issue 타입 ('x' 로 표기)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert (Rollback)

### 상세 내용
- Data lake 구축
- raw, cleaned, curated 단계로 나누어야 함

### 예상 소요 시간
- [x] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by ssongjj** [comment]
S3 환경 구축 완료 및 버킷 내 폴더 구조에 맞추어 생성.
<img width="330" alt="image" src="https://github.com/FlaschenbookProject/Flaschenbook/assets/39427152/4254e2cd-95e2-4ec7-876f-2c08e3beeb5c">
