### ISSUE TITLE
AWS Redshift (Data warehouse) 환경구축

### ISSUE THREAD

**Issue by ujeongoh** [FlaschenbookProject/Flaschenbook#23]
### Issue 타입 ('x' 로 표기)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert (Rollback)

### 상세 내용
- AWS Redshift cluster 구축

### 예상 소요 시간
- [x] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by ssongjj** [comment]
Redshift 환경은 처음 구성했던 클러스터 생성 대신 Serverless 환경으로 구축하였습니다.
