### ISSUE TITLE
S3 내부 데이터 작업 로직 구현

### ISSUE THREAD

**Issue by ssongjj** [FlaschenbookProject/Flaschenbook#66]
### Issue 타입 ('x' 로 표기)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert (Rollback)

### 상세 내용
- S3 내부에서 raw 데이터를 cleaning 작업하여 cleaned에 적재
- cleaned 데이터를 최종 Data Warehouse에 적재할 수 있는 curated 데이터로 만들어 적재
- S3 내부 데이터 로직 구현 

### 예상 소요 시간
- [ ] `0.5h`
- [ ] `1h`
- [x] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

### 참고사항
- lambda, airflow를 후보로 두고 더 적절한 것을 사용하여 진행

**Comment by ujeongoh** [comment]
* raw -> cleaned -> curated 작업은 lambda 사용하였고, 정해진 s3 경로로 object가 put되면 trigger되어 lambda함수가 실행되게 구현하였습니다.
* TODO : curated 로 적재하는 lambda함수가 완료되면 SQS에 메세지를 발송하고, Glue가 읽어서 curated data를 rds db에 적재하는 파이프라인을 구현해야합니다.
